// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://entdtzsocrippwnuwmbk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVudGR0enNvY3JpcHB3bnV3bWJrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxNDYyNDksImV4cCI6MjA1ODcyMjI0OX0.XrZLHfee-LChYaqiWjY-oRfBLyRFFcsjzWCVCFhKEIU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);