// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gqlczfdeopmuzevodcvd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdxbGN6ZmRlb3BtdXpldm9kY3ZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwNTY1OTMsImV4cCI6MjA1ODYzMjU5M30.TyRnv5EnBshQmWr5jTxkzDnS5LS7ODz6keYzIGw2fpc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);